name: PHPUnit
run-name: ${{ github.actor }} is testing out Github Actions
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          extensions: sqlite, sqlite3, mbstring, zip, xml, gd, dom
      - uses: php-actions/composer@v6
      - run: ./vendor/bin/phpunit --coverage-cobertura=coverage.cobertura.xml
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: file
          thresholds: '60 80'
      - name: Adding markdown
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      - name: PHP Mess Detector
        uses: php-actions/phpmd@v1
        with:
          path: lib/
          output: text
          ruleset: phpmd.xml
      - name: copy files via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: "13.48.50.234"
          username: ubuntu
          key: ${{secrets.KEY}}
          source: "*"
          target: /srv
      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          path: lib/
          standard: phpcs.xml
