name: PHPUnit
run-name: ${{ github.actor }} is testing out Github Actions
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          extensions: sqlite, sqlite3, mbstring, zip, xml, gd, dom
      - run: sudo apt install php8.1-gd
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          version: 9.6.11
